# Required status checks that must pass before merging:
required_status_checks:
  strict: true
  contexts:
    - "lint"
    - "test"

# 1 review required for pull request
required_pull_request_reviews:
  required_approving_review_count: 1
  dismiss_stale_reviews: true
  require_code_owner_reviews: true
  require_last_push_approval: true

# Restrictions on who pushes to main
restrictions:
  users: []
  teams: []

# Additional protections
enforce_admins: true
allow_force_pushes: false
allow_deletions: false
