FROM python:3.10-slim

# Working dir
WORKDIR /app

ENV FLASK_CONFIG=config.DevelopmentConfig
ENV FLASK_APP=application.wsgi:app
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000
ENV FLASK_DEBUG=1

# install system deps
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    postgresql-client rsync make \
    git curl build-essential libpq-dev bash && \
    curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y --no-install-recommends nodejs && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /venv

ENV PATH="/venv/bin:$PATH"

##### Todo: For development only
ENV NODE_NO_WARNINGS=1
ENV NO_UPDATE_NOTIFIER=1
# Skip verification
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
ENV GIT_SSL_NO_VERIFY=1
RUN npm config set update-notifier false && \
    npm config set strict-ssl false
##### Todo: For development only

# Copy application source
COPY . .

# Install deps
RUN npm install && \
	python -m pip install --upgrade pip setuptools wheel && \
	python -m pip install -r requirements.txt

EXPOSE 5000

ENTRYPOINT ["sh", "-c", "flask db upgrade && flask run --debug"]
