"""add versioning and publication status

Revision ID: 027496d55f55
Revises: f8c9f47c8797
Create Date: 2023-03-16 15:31:13.375564

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "027496d55f55"
down_revision = "f8c9f47c8797"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    publication_status = sa.Enum("DRAFT", "PUBLISHED", name="publication_status")

    publication_status.create(op.get_bind())

    with op.batch_alter_table("_default", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("publication_status", publication_status, nullable=False)
        )

    with op.batch_alter_table("column", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("publication_status", publication_status, nullable=False)
        )

    with op.batch_alter_table("combine", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("publication_status", publication_status, nullable=False)
        )

    with op.batch_alter_table("concat", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("publication_status", publication_status, nullable=False)
        )

    with op.batch_alter_table("convert", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("publication_status", publication_status, nullable=False)
        )

    with op.batch_alter_table("default_value", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("publication_status", publication_status, nullable=False)
        )

    with op.batch_alter_table("endpoint", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("publication_status", publication_status, nullable=False)
        )

    with op.batch_alter_table("filter", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("publication_status", publication_status, nullable=False)
        )

    with op.batch_alter_table("lookup", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("publication_status", publication_status, nullable=False)
        )

    with op.batch_alter_table("patch", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("publication_status", publication_status, nullable=False)
        )

    with op.batch_alter_table("skip", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("publication_status", publication_status, nullable=False)
        )

    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("publication_status", publication_status, nullable=False)
        )

    with op.batch_alter_table("transform", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("publication_status", publication_status, nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transform", schema=None) as batch_op:
        batch_op.drop_column("publication_status")
        batch_op.drop_column("version_id")

    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.drop_column("publication_status")
        batch_op.drop_column("version_id")

    with op.batch_alter_table("skip", schema=None) as batch_op:
        batch_op.drop_column("publication_status")
        batch_op.drop_column("version_id")

    with op.batch_alter_table("patch", schema=None) as batch_op:
        batch_op.drop_column("publication_status")
        batch_op.drop_column("version_id")

    with op.batch_alter_table("lookup", schema=None) as batch_op:
        batch_op.drop_column("publication_status")
        batch_op.drop_column("version_id")

    with op.batch_alter_table("filter", schema=None) as batch_op:
        batch_op.drop_column("publication_status")
        batch_op.drop_column("version_id")

    with op.batch_alter_table("endpoint", schema=None) as batch_op:
        batch_op.drop_column("publication_status")
        batch_op.drop_column("version_id")

    with op.batch_alter_table("default_value", schema=None) as batch_op:
        batch_op.drop_column("publication_status")
        batch_op.drop_column("version_id")

    with op.batch_alter_table("convert", schema=None) as batch_op:
        batch_op.drop_column("publication_status")
        batch_op.drop_column("version_id")

    with op.batch_alter_table("concat", schema=None) as batch_op:
        batch_op.drop_column("publication_status")
        batch_op.drop_column("version_id")

    with op.batch_alter_table("combine", schema=None) as batch_op:
        batch_op.drop_column("publication_status")
        batch_op.drop_column("version_id")

    with op.batch_alter_table("column", schema=None) as batch_op:
        batch_op.drop_column("publication_status")
        batch_op.drop_column("version_id")

    with op.batch_alter_table("_default", schema=None) as batch_op:
        batch_op.drop_column("publication_status")
        batch_op.drop_column("version_id")

    op.execute("DROP TYPE publication_status")

    # ### end Alembic commands ###
