"""add pipeline and source_pipeline

Revision ID: 31096d9328f6
Revises: 7ed1870dd261
Create Date: 2022-02-17 11:32:39.332213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "31096d9328f6"
down_revision = "7ed1870dd261"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline",
        sa.Column("_entry_date", sa.Date(), nullable=True),
        sa.Column("_start_date", sa.Date(), nullable=True),
        sa.Column("_end_date", sa.Date(), nullable=True),
        sa.Column("pipeline", sa.Text(), nullable=False),
        sa.Column("schema", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("pipeline"),
    )
    op.create_table(
        "source_pipeline",
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("pipeline", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pipeline"],
            ["pipeline.pipeline"],
        ),
        sa.ForeignKeyConstraint(
            ["source"],
            ["source.source"],
        ),
        sa.PrimaryKeyConstraint("source", "pipeline"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("source_pipeline")
    op.drop_table("pipeline")
    # ### end Alembic commands ###
