"""move publication status to collection and pipeline

Revision ID: 5dbe33b2bfb5
Revises: 027496d55f55
Create Date: 2023-03-27 16:39:58.380770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5dbe33b2bfb5"
down_revision = "027496d55f55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("_default", schema=None) as batch_op:
        batch_op.drop_column("publication_status")

    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "publication_status",
                sa.Enum("DRAFT", "PUBLISHED", name="publication_status"),
                nullable=True,
            )
        )

    with op.batch_alter_table("column", schema=None) as batch_op:
        batch_op.drop_column("publication_status")

    with op.batch_alter_table("combine", schema=None) as batch_op:
        batch_op.drop_column("publication_status")

    with op.batch_alter_table("concat", schema=None) as batch_op:
        batch_op.drop_column("publication_status")

    with op.batch_alter_table("convert", schema=None) as batch_op:
        batch_op.drop_column("publication_status")

    with op.batch_alter_table("default_value", schema=None) as batch_op:
        batch_op.drop_column("publication_status")

    with op.batch_alter_table("endpoint", schema=None) as batch_op:
        batch_op.drop_column("publication_status")

    with op.batch_alter_table("filter", schema=None) as batch_op:
        batch_op.drop_column("publication_status")

    with op.batch_alter_table("lookup", schema=None) as batch_op:
        batch_op.drop_column("publication_status")

    with op.batch_alter_table("patch", schema=None) as batch_op:
        batch_op.drop_column("publication_status")

    with op.batch_alter_table("pipeline", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "publication_status",
                sa.Enum("DRAFT", "PUBLISHED", name="publication_status"),
                nullable=True,
            )
        )

    with op.batch_alter_table("skip", schema=None) as batch_op:
        batch_op.drop_column("publication_status")

    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.drop_column("publication_status")

    with op.batch_alter_table("transform", schema=None) as batch_op:
        batch_op.drop_column("publication_status")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transform", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "publication_status",
                postgresql.ENUM("DRAFT", "PUBLISHED", name="publication_status"),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "publication_status",
                postgresql.ENUM("DRAFT", "PUBLISHED", name="publication_status"),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("skip", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "publication_status",
                postgresql.ENUM("DRAFT", "PUBLISHED", name="publication_status"),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("pipeline", schema=None) as batch_op:
        batch_op.drop_column("publication_status")

    with op.batch_alter_table("patch", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "publication_status",
                postgresql.ENUM("DRAFT", "PUBLISHED", name="publication_status"),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("lookup", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "publication_status",
                postgresql.ENUM("DRAFT", "PUBLISHED", name="publication_status"),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("filter", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "publication_status",
                postgresql.ENUM("DRAFT", "PUBLISHED", name="publication_status"),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("endpoint", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "publication_status",
                postgresql.ENUM("DRAFT", "PUBLISHED", name="publication_status"),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("default_value", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "publication_status",
                postgresql.ENUM("DRAFT", "PUBLISHED", name="publication_status"),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("convert", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "publication_status",
                postgresql.ENUM("DRAFT", "PUBLISHED", name="publication_status"),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("concat", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "publication_status",
                postgresql.ENUM("DRAFT", "PUBLISHED", name="publication_status"),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("combine", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "publication_status",
                postgresql.ENUM("DRAFT", "PUBLISHED", name="publication_status"),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("column", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "publication_status",
                postgresql.ENUM("DRAFT", "PUBLISHED", name="publication_status"),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.drop_column("publication_status")

    with op.batch_alter_table("_default", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "publication_status",
                postgresql.ENUM("DRAFT", "PUBLISHED", name="publication_status"),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
