"""set org fk to lookup nullable

Revision ID: 67684c33a6c2
Revises: 3779eb2ce2f1
Create Date: 2023-02-28 18:17:12.414839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "67684c33a6c2"
down_revision = "3779eb2ce2f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lookup", schema=None) as batch_op:
        batch_op.alter_column("organisation_id", existing_type=sa.TEXT(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
