"""add resources

Revision ID: 9dd1ab7d14f1
Revises: ec230bea244f
Create Date: 2022-02-15 13:01:40.595072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9dd1ab7d14f1"
down_revision = "ec230bea244f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource",
        sa.Column("resource", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("bytes", sa.Integer(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("resource"),
    )
    op.create_table(
        "resource_endpoint",
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("resource", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint"],
            ["endpoint.endpoint"],
        ),
        sa.ForeignKeyConstraint(
            ["resource"],
            ["resource.resource"],
        ),
        sa.PrimaryKeyConstraint("endpoint", "resource"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resource_endpoint")
    op.drop_table("resource")
    # ### end Alembic commands ###
