"""add tables needed for fields

Revision ID: c6cf4bb78ece
Revises: 163ffa84701a
Create Date: 2022-02-28 15:50:44.317791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c6cf4bb78ece"
down_revision = "163ffa84701a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datatype",
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("datatype", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("datatype"),
    )
    op.create_table(
        "field",
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("field", sa.Text(), nullable=False),
        sa.Column("cardinality", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("guidance", sa.Text(), nullable=True),
        sa.Column("hint", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("parent_field", sa.Text(), nullable=True),
        sa.Column("replacement_field", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("uri_template", sa.Text(), nullable=True),
        sa.Column("wikidata_property", sa.Text(), nullable=True),
        sa.Column("datatype_id", sa.Text(), nullable=True),
        sa.Column("typology_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["datatype_id"],
            ["datatype.datatype"],
        ),
        sa.ForeignKeyConstraint(
            ["typology_id"],
            ["typology.typology"],
        ),
        sa.PrimaryKeyConstraint("field"),
    )
    op.create_table(
        "column",
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("column", sa.Text(), nullable=False),
        sa.Column("dataset_id", sa.Text(), nullable=True),
        sa.Column("field_id", sa.Text(), nullable=True),
        sa.Column("resource_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.dataset"],
        ),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["field.field"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resource.resource"],
        ),
        sa.PrimaryKeyConstraint("column"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("column")
    op.drop_table("field")
    op.drop_table("datatype")
    # ### end Alembic commands ###
