"""add date properties to base model and inherit

Revision ID: d09ee6215f13
Revises: 9dd1ab7d14f1
Create Date: 2022-02-16 13:47:38.853845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d09ee6215f13"
down_revision = "9dd1ab7d14f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("collection", "entry_date", new_column_name="_entry_date")
    op.alter_column("collection", "start_date", new_column_name="_start_date")
    op.alter_column("collection", "end_date", new_column_name="_end_date")

    op.alter_column("dataset", "entry_date", new_column_name="_entry_date")
    op.alter_column("dataset", "start_date", new_column_name="_start_date")
    op.alter_column("dataset", "end_date", new_column_name="_end_date")

    op.alter_column("endpoint", "entry_date", new_column_name="_entry_date")
    op.alter_column("endpoint", "start_date", new_column_name="_start_date")
    op.alter_column("endpoint", "end_date", new_column_name="_end_date")

    op.alter_column("organisation", "entry_date", new_column_name="_entry_date")
    op.alter_column("organisation", "start_date", new_column_name="_start_date")
    op.alter_column("organisation", "end_date", new_column_name="_end_date")

    op.alter_column("resource", "entry_date", new_column_name="_entry_date")
    op.alter_column("resource", "start_date", new_column_name="_start_date")
    op.alter_column("resource", "end_date", new_column_name="_end_date")

    op.alter_column("source", "entry_date", new_column_name="_entry_date")
    op.alter_column("source", "start_date", new_column_name="_start_date")
    op.alter_column("source", "end_date", new_column_name="_end_date")

    op.alter_column("typology", "entry_date", new_column_name="_entry_date")
    op.alter_column("typology", "start_date", new_column_name="_start_date")
    op.alter_column("typology", "end_date", new_column_name="_end_date")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("collection", "_entry_date", new_column_name="entry_date")
    op.alter_column("collection", "_start_date", new_column_name="start_date")
    op.alter_column("collection", "_end_date", new_column_name="end_date")

    op.alter_column("dataset", "_entry_date", new_column_name="entry_date")
    op.alter_column("dataset", "_start_date", new_column_name="start_date")
    op.alter_column("dataset", "_end_date", new_column_name="end_date")

    op.alter_column("endpoint", "_entry_date", new_column_name="entry_date")
    op.alter_column("endpoint", "_start_date", new_column_name="start_date")
    op.alter_column("endpoint", "_end_date", new_column_name="end_date")

    op.alter_column("organisation", "_entry_date", new_column_name="entry_date")
    op.alter_column("organisation", "_start_date", new_column_name="start_date")
    op.alter_column("organisation", "_end_date", new_column_name="end_date")

    op.alter_column("resource", "_entry_date", new_column_name="entry_date")
    op.alter_column("resource", "_start_date", new_column_name="start_date")
    op.alter_column("resource", "_end_date", new_column_name="end_date")

    op.alter_column("source", "_entry_date", new_column_name="entry_date")
    op.alter_column("source", "_start_date", new_column_name="start_date")
    op.alter_column("source", "_end_date", new_column_name="end_date")

    op.alter_column("typology", "_entry_date", new_column_name="entry_date")
    op.alter_column("typology", "_start_date", new_column_name="start_date")
    op.alter_column("typology", "_end_date", new_column_name="end_date")

    # ### end Alembic commands ###
