"""add source check table

Revision ID: eb1a3fcba74e
Revises: 55fc7342e00d
Create Date: 2022-03-23 12:18:43.627541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "eb1a3fcba74e"
down_revision = "55fc7342e00d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_check",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=True),
        sa.Column("resource_hash", sa.Text(), nullable=True),
        sa.Column(
            "resource_rows", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("resource_fields", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("created_timestamp", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.source"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("source_check")
    # ### end Alembic commands ###
